version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 3600
  BeforeInstall:
    - location: before_install.sh
  ApplicationStart:
    - location: application_start.sh
      timeout: 3600
