version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 3600
  BeforeInstall:
    - location: install_go_libs.sh
  ApplicationStart:
    - location: run.sh
      timeout: 3600
